- import_playbook: plays/ansible.yml
- name: vars
  gather_facts: no
  hosts: all
  no_log: true
  tasks:
    - name: load vars
      include_vars:
        dir: vars
        files_matching: '.*\.yml'
    - name: set server facts
      set_fact:
        dbRootPassword: '!!12345'
        tmcomDBPassword: '!!12345'
        dbBackupPassword: '!!12345'
        dwDBPassword: '!!12345'
        tifDBPassword: '!!12345'
        tmcomEnv: dev
- import_playbook: plays/main.yml
- name: dev
  become: true
  hosts: all
  tasks:
    - name: var folder dir sources
      file:
        path: "/var/www/var/{{item.site}}/{{item.src}}"
        state: directory
      with_items: "{{devVarDirs}}"
    - name: var folder dir destinations
      file:
        src: "/var/www/var/{{item.site}}/{{item.src}}"
        path: "/var/www/sites/{{item.site}}/{{item.dest}}"
        state: link
      with_items: "{{devVarDirs}}"
