- import_playbook: plays/ansible.yml
- name: vars
  gather_facts: no
  hosts: all
  no_log: true
  tasks:
    - name: load vars
      include_vars:
        dir: vars
        files_matching: '.*\.yml$'
    - name: load dev vars
      include_vars:
        dir: vars.dev
        files_matching: '.*\.yml$'
    - name: inject dev vars to existing
      no_log: false
      set_fact:
        sites: "{{ sites | combine(devSites) }}"
- import_playbook: plays/main.yml
- import_playbook: plays/dev/sites-var.yml
