- name: install build software
  become: true
  hosts: all
  tasks:
    - name: install php
      apt:
        name:
          - php
          - php-cli
          - php-gd
          - phpunit
        state: present
    - name: install css build packages
      apt:
        name:
          - node-postcss
          - sassc
        state: present
    - name: install js build packages
      apt:
        name:
          - npm
          - rollup
          - uglifyjs
          - yarnpkg
        state: present
