- name: install db
  become: true
  hosts: all
  tasks:
    - name: install mysql
      apt:
        name:
          - mysql-client
          - mysql-server
          - python3-pymysql #--for mysql_user module
        state: present
- name: configure db
  become: true
  hosts: all
  tasks:
    - name: set root mysql password
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: root
        password: '{{dbRootPassword}}'
        state: present
      no_log: true
    - name: add root my.cnf for future logins
      no_log: true
      template:
        dest: /root/.my.cnf
        mode: 0600
        src: ../../assets/root/.my.cnf
