- name: install certbot
  become: true
  handlers:
    - import_tasks: ../handlers.yml
  hosts: public
  tasks:
    - name: install certbot cli
      apt:
        name: certbot
        state: present
    - name: create shared webroot for certbot well-known
      file:
        group: www-data
        mode: '2750'
        path: /var/www/letsencrypt
        state: directory
    - name: install letsencrypt apache conf
      copy:
        dest: /etc/apache2/conf-enabled/letsencrypt.conf
        src: ../../assets/etc/apache2/conf-enabled/letsencrypt.conf
      notify: 'apache conf change'
    - name: check if certbot set up
      stat:
        get_attributes: false
        get_checksum: false
        get_mime: false
        path: /etc/letsencrypt/accounts
      register: certbotAccountsStat
    - name: set up deploy hook
      copy:
        dest: /etc/letsencrypt/renewal-hooks/deploy/deploy.sh
        group: root
        mode: '0750'
        owner: root
        src: ../../assets/etc/letsencrypt/renewal-hooks/deploy/deploy.sh
    - name: set up certs
      command: 'certbot certonly --agree-tos --cert-name {{item.key}} --expand --keep -m admin@tobymackenzie.com -n --webroot --webroot-path /var/www/letsencrypt/ -d {{item.value.domains|default(item.key.split(" "))|join(" -d ")}}'
      changed_when: "'Your certificate and chain have been saved' in certbotResults"
      register: certbotResults
      when: certbotAccountsStat.stat.isdir is defined and certbotAccountsStat.stat.isdir
      with_dict: '{{httpsCerts}}'
