- name: install lamp
  become: true
  hosts: all
  tasks:
    - name: install apache
      apt:
        name: apache2
        state: present
    - name: install mysql
      apt:
        name:
          - mysql-client
          - mysql-server
          - php-mysql
          - python-mysqldb #--for mysql_user module
        state: present
    - name: install php
      apt:
        name:
          - php
          - php-cli
          - php-curl
          - php-fpm
          - php-intl
          - php-mbstring
          - php-mysql
          - php-xml
          - php-zip #-- for composer
        state: present
    - name: check composer's existence
      stat:
        path: '/usr/local/bin/composer'
      register: isComposerInstalled
    - name: get composer
      get_url:
        dest: /tmp/composerInstall
        url: https://getcomposer.org/installer
      when: isComposerInstalled.stat.exists != true
    - name: build composer
      become: true
      become_user: '{{adminUser}}' #--limited privileges
      command: 'php /tmp/composerInstall --filename=composer --install-dir=/tmp'
      when: isComposerInstalled.stat.exists != true
    - name: install composer
      command: 'mv /tmp/composer /usr/local/bin/composer'
      when: isComposerInstalled.stat.exists != true
    - name: clean composer installation
      file:
        path: /tmp/composerInstall
        state: absent
      when: isComposerInstalled.stat.exists != true
    - name: set composer permissions
      file:
        group: '{{adminUser}}' #--allow limited privilege updates
        mode: 0775
        owner: root
        path: /usr/local/bin/composer
