#-@ https://ryaneschinger.com/blog/securing-a-server-with-ansible/
- name: secure server
  become: true
  handlers:
    - import_tasks: ../handlers.yml
  hosts: all
  tasks:
    - name: disallow root ssh
      lineinfile:
        dest: /etc/ssh/sshd_config
        line: 'PermitRootLogin no'
        regexp: '^PermitRootLogin'
        state: present
      notify: restart ssh
    - name: prevent ssh password auth
      lineinfile:
        dest: /etc/ssh/sshd_config
        line: 'PasswordAuthentication no'
        regexp: '^PasswordAuthentication'
        state: present
      notify: restart ssh
    - name: install security packages
      apt:
        name:
          - 'fail2ban'
          - 'ufw'
        state: present
    - name: block all ports by default
      ufw:
        policy: deny
        state: enabled
    - name: configure allowed ports
      ufw:
        port: '{{item.port}}'
        proto: '{{item.proto}}'
        rule: allow
      with_items:
        - '{{fw_allow}}'
- name: manage filesystem permissions
  become: true
  hosts: all
  tasks:
    - name: allow staff to edit '/usr/local/bin' files
      file:
        group: staff #--allow limited privilege updates
        mode: '2775'
        owner: root
        path: /usr/local/bin
