- name: set up default user
  become: true
  hosts: all
  tasks:
    - name: set default user shell
      lineinfile:
        dest: '/etc/default/useradd'
        line: 'SHELL=/bin/bash'
        regexp: '^SHELL='
        state: present
#--server administrator
- name: set up admin user
  become: true
  hosts: all
  tasks:
    - name: add to admin groups
      user:
        append: yes
        groups:
          - staff #--allow installing to /usr/local/bin
          - sudo #--allow sudo
        name: '{{adminUser}}'
    - name: install ssh key
      lineinfile:
        dest: '/home/{{adminUser}}/.ssh/authorized_keys'
        line: '{{tmKey}}'
        state: present
#--vagrant
- name: set up vagrant user
  become: true
  hosts: default #-! means vagrant. we should fix this by renaming vagrant box to dev
  tasks:
    #-! we do this because we want to be able to rsync normally, but many of the files are owned by vagrant. we should change them to be owned by adminUser, connect with that user, and then we won't need this
    - name: install ssh key
      lineinfile:
        dest: '/home/vagrant/.ssh/authorized_keys'
        line: '{{tmKey}}'
        state: present
#-!! should have an unprivileged user for owning and editing web files
